import {Metadata} from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import './globals.css'
import {ErrorWrapper} from "@/app/error-wrapper";
export const metadata: Metadata = {
    title: {
        default:"NextJs Tutorial - Codevolution", // Fallback For Child Routes
        template:"%s | Codevolution",
    },
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <ErrorWrapper>
            <Header/>
            {children}
            <Footer/>
        </ErrorWrapper>
        </body>
        </html>
    )
}
