import {Metadata} from "next";
import Link from "next/link";
import "./globals.css"
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Header/>
        <main className="flex">
            <Sidebar/>
            <div className="w-full">
                {children}
            </div>
        </main>
        <Footer/>
        </body>
        </html>
    )
}
