import {Metadata} from "next";
import './global.css'
import {dbConnect} from "@/lib/mongo";

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode
}) {
    const conn = await dbConnect();
    console.log(conn);
    return (
        <html lang="en">
        <body>
        {children}
        </body>
        </html>
    )
}
